name: 'sfdx-cicd'
description: 'Use sfdx/sfpowerkit to validate or deploy a diff deploy'
inputs:
  validate-only:
    description: 'When pushing to org, should we only validate or actually deploy'
    required: true
    default: 'true'
  test-level:
    description: 'When pushing to org, sets the level of tests that should run: RunLocalTests - run all tests minus
      managed packed tests in target; RunSpecifiedTests - only runs the provided test classes; NoTestRun - no tests
      run. Production requires test classes to run if Apex is deployed. For Dev blank is default-NoTestRun, Prod default-RunLocalTests'
    required: false
    default: ''
  specified-tests:
    description: 'When running tests on the target org, set specified tests to run only when test-level is RunSpecifiedTest. Must be a comma delimmited
    list of Apex Classes'
    required: false
    default: ''
  sfdx-auth-url:
    description: 'SFDX Login url for org'
    required: true
  revision-from:
    description: 'Base revision from where the diff is generated'
    required: true
    default: 'origin/main'
  revision-to:
    description: 'Target revision to generate the diff'
    required: true
    default: 'HEAD'
  api-version:
    description: 'Metadata API version to use during retrieve/deploy (used only when sourceApiVersion is
      not specified in your sfdx-project.json file). If sourceApiVersion IS specified in the sfdx-project.json
      file, that value OVERRIDES anything specified here. If NO values are specified (here or in sfdx-project.json),
      defaults to the current highest API version for the org.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    # Checkout full repo, needed to do diff
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    # Checkout NPM
    - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'

    # Install dependencies
    - name: Install Dependencies
      run: npm ci
    
    # Add NPM modules to the path
    -name: Update GITHUB_PATH
      run: echo "$(pwd)/node_modules/.bin" >> $GITHUB_PATH

    - run: ${{ github.action_path }}/sfdx-cicd.sh
      shell: bash
      env:
        VALIDATE_ONLY: ${{ inputs.validate-only }}
        TEST_LEVEL: ${{ inputs.test-level }}
        SPECIFIED_TESTS: ${{ inputs.specified-tests }}
        SFDX_AUTH_URL: ${{ inputs.sfdx-auth-url }}
        REVISION_FROM: ${{ inputs.revision-from }}
        REVISION_TO: ${{ inputs.revision-to }}
        API_VERSION: ${{ inputs.api-version }}
