name: 'sfdx-cicd'
description: 'Use sfdx/sfpowerkit to validate or deploy a diff deploy'
inputs:
  validate-only:
    description: 'When pushing to org, should we only validate or actually deploy'
    required: true
    default: 'true'
  test-level:
    description: 'When pushing to org, sets the level of tests that should run'
    required: false
    default: 'NoTests'
  specified-tests:
    description: 'When running tests on the target org, set specified tests to run'
    required: false
    default: ''
  sfdx-auth-url:
    description: 'SFDX Login url for org'
    required: true
  revision-from:
    description: 'Base revision from where the diff is generated'
    required: true
    default: 'origin/main'
  revision-to:
    description: 'Target revision to generate the diff'
    required: true
    default: 'HEAD'
  api-version:
    description: 'SF API version to use during validate/deploy'
    required: true
    default: '51.0'
  sfdx-download-url:
    description: 'URL to download SFDX Linux client. Uses the XZ compressed version. Default is the stable version. Other version available at https://developer.salesforce.com/media/salesforce-cli/sfdx/versions/sfdx-linux-arm-tar-xz.json'
    required: true
    default: 'https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz'

runs:
  using: 'composite'
  steps:
    # Checkout full repo, needed to do diff
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - run: ${{ github.action_path }}/sfdx-cicd.sh
      shell: bash
      env:
        VALIDATE_ONLY: ${{ inputs.validate-only }}
        TEST_LEVEL: ${{ inputs.test-level }}
        SPECIFIED_TESTS: ${{ inputs.specified-tests }}
        SFDX_AUTH_URL: ${{ inputs.sfdx-auth-url }}
        REVISION_FROM: ${{ inputs.revision-from }}
        REVISION_TO: ${{ inputs.revision-to }}
        API_VERSION: ${{ inputs.api-version }}
        SFDX_DOWNLOAD_URL: ${{ inputs.sfdx-download-url }}