name: 'sfdx-cicd'
description: 'Use sfdx/sfpowerkit to validate or deploy a diff deploy'
inputs:
  validate-only:
    description: 'When pushing to org, should we only validate or actually deploy'
    required: true
    default: true
  sfdx-auth-url:
    description: 'SFDX Login url for org'
    required: true
  revision-from:
    description: 'Base revision from where the diff is generated'
    required: true
    default: 'origin/main'
  revision-to:
    description: 'Target revision to generate the diff'
    required: true
    default: 'HEAD'
  api-version:
    description: 'SF API version to use during validate/deploy'
    default: '51.0'

runs:
  using: 'composite'
  steps:
    # Checkout full repo, needed to do diff
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    # Using stable version
    - name: Install SFDX CLI
      shell: bash
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
        mkdir ~/sfdx-cli
        tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx-cli --strip-components 1
        export PATH=~/sfdx-cli/bin:$PATH
    
    - name: Echo path
      shell: bash
      run: |
        echo "Echoing path"
        echo $PATH

    - name: Install SFPowerkit
      shell: bash
      run: echo 'y' | sfdx plugins:install sfpowerkit
        
    - name: Echo vars
      shell: bash
      run: echo $VALIDATE_ONLY
    
    - name: Set validate/deploy flag
      shell: bash
      run: if [[ $VALIDATE_ONLY = true ]]; then VALIDATE_FLAG='-c'; else VALIDATE_FLAG=''; fi
      
    - name: Echo validate flag
      shell: bash
      run: echo $VALIDATE_FLAG
    
    # SFDX needs this file to auth
    - name: Create auth file from secret
      shell: bash
      run: echo ${{ inputs.sfdx-auth-url }} > SFDX_AUTH
      
    - name: Auth SF Org
      shell: bash
      run: sfdx force:auth:sfdxurl:store -f SFDX_AUTH -s -a SFOrg
      
    - name: Diff repo with Org
      shell: bash
      run: sfdx sfpowerkit:project:diff -r {{ inputs.revision-from }} -t {{ inputs.revision-to }} -d diffdeploy

    - name: Validate deploy
      shell: bash
      run: sfdx force:source:deploy -p diffdeploy/force-app -u SFOrg --json --loglevel fatal -c --apiversion={{ inputs.api-version }}
    
    
  
#   args:
#     - '--action=${{inputs.action}}'
#     - '--sfdx-auth-url=${{inputs.sfdx-auth-url}}'
#     - '--revision-from=${{inputs.revision-from}}'
#     - '--revision-to=${{inputs.revision-to}}'
